
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftDIVVEZESleftMAISleftEXPAPAR DIV EXP FPAR MAIS MENOS NUM VEZESexp : exp MAIS exp exp : exp DIV exp exp : exp VEZES exp exp : exp EXP exp exp : APAR exp FPAR exp : NUM '
    
_lr_action_items = {'APAR':([0,2,4,5,6,7,],[2,2,2,2,2,2,]),'NUM':([0,2,4,5,6,7,],[3,3,3,3,3,3,]),'$end':([1,3,9,10,11,12,13,],[0,-6,-1,-2,-3,-4,-5,]),'MAIS':([1,3,8,9,10,11,12,13,],[4,-6,4,-1,4,4,-4,-5,]),'DIV':([1,3,8,9,10,11,12,13,],[5,-6,5,-1,-2,-3,-4,-5,]),'VEZES':([1,3,8,9,10,11,12,13,],[6,-6,6,-1,-2,-3,-4,-5,]),'EXP':([1,3,8,9,10,11,12,13,],[7,-6,7,7,7,7,-4,-5,]),'FPAR':([3,8,9,10,11,12,13,],[-6,13,-1,-2,-3,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,2,4,5,6,7,],[1,8,9,10,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> exp MAIS exp','exp',3,'p_expMAIS','sintatico_calculadora.py',11),
  ('exp -> exp DIV exp','exp',3,'p_expDIV','sintatico_calculadora.py',15),
  ('exp -> exp VEZES exp','exp',3,'p_expVEZES','sintatico_calculadora.py',20),
  ('exp -> exp EXP exp','exp',3,'p_expEXP','sintatico_calculadora.py',25),
  ('exp -> APAR exp FPAR','exp',3,'p_expPAR','sintatico_calculadora.py',30),
  ('exp -> NUM','exp',1,'p_expNUM','sintatico_calculadora.py',35),
]
